/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service information */
        get: operations["service_info__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query the catalog */
        get: operations["get_catalog_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Object detail */
        get: operations["get_object_detail_catalog__object_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{object_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Object element-set history */
        get: operations["get_object_history_catalog__object_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{object_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Object latest state */
        get: operations["get_object_latest_state_catalog__object_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Celestrak ingest */
        post: operations["run_ingest_ingest_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest propagated state */
        get: operations["get_latest_state_state_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live latest-state stream (SSE)
         * @description Push the latest propagated snapshot on each propagation cycle (one-way SSE).
         *
         *     Lets the dashboard receive live-state deltas without polling; the browser
         *     interpolates between snapshots (dev-plan §4.2/§4.5).
         */
        get: operations["state_stream_state_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alert stream (SSE) */
        get: operations["alerts_stream_alerts_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CatalogObject */
        CatalogObject: {
            /** Object Id */
            object_id: string;
            /** Norad Cat Id */
            norad_cat_id?: number | null;
            /** Object Name */
            object_name: string;
            /** Object Type */
            object_type?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Tle Line0 */
            tle_line0?: string | null;
            /** Tle Line1 */
            tle_line1?: string | null;
            /** Tle Line2 */
            tle_line2?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryPoint
         * @description One element set in an object's time series (gp_history).
         */
        HistoryPoint: {
            /** Object Id */
            object_id: string;
            /**
             * Epoch
             * Format: date-time
             */
            epoch: string;
            /** Data Source */
            data_source?: string | null;
            /** Mean Motion */
            mean_motion?: number | null;
            /** Eccentricity */
            eccentricity?: number | null;
            /** Inclination */
            inclination?: number | null;
            /** Ra Of Asc Node */
            ra_of_asc_node?: number | null;
            /** Arg Of Pericenter */
            arg_of_pericenter?: number | null;
            /** Mean Anomaly */
            mean_anomaly?: number | null;
            /** Bstar */
            bstar?: number | null;
            /** Semimajor Axis Km */
            semimajor_axis_km?: number | null;
            /** Period Min */
            period_min?: number | null;
            /** Apoapsis Km */
            apoapsis_km?: number | null;
            /** Periapsis Km */
            periapsis_km?: number | null;
        };
        /** IngestResult */
        IngestResult: {
            /** Written */
            written: number;
        };
        /** LatestState */
        LatestState: {
            /** Generated At */
            generated_at?: string | null;
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Objects */
            objects?: components["schemas"]["StateObject"][];
        };
        /** Liveness */
        Liveness: {
            /** @default ok */
            status: components["schemas"]["LivenessStatus"];
        };
        /**
         * LivenessStatus
         * @enum {string}
         */
        LivenessStatus: "ok";
        /**
         * ObjectDetail
         * @description Full catalog record for the per-satellite info sidebar (#9h).
         */
        ObjectDetail: {
            /** Object Id */
            object_id: string;
            /** Norad Cat Id */
            norad_cat_id?: number | null;
            /** Intl Designator */
            intl_designator?: string | null;
            /** Data Source */
            data_source?: string | null;
            /** Originator */
            originator?: string | null;
            /** Object Name */
            object_name: string;
            /** Object Type */
            object_type?: string | null;
            /** Rcs Size */
            rcs_size?: string | null;
            /** Classification Type */
            classification_type?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Launch Date */
            launch_date?: string | null;
            /** Decay Date */
            decay_date?: string | null;
            /** Site */
            site?: string | null;
            /** Epoch */
            epoch?: string | null;
            /** Mean Motion */
            mean_motion?: number | null;
            /** Eccentricity */
            eccentricity?: number | null;
            /** Inclination */
            inclination?: number | null;
            /** Ra Of Asc Node */
            ra_of_asc_node?: number | null;
            /** Arg Of Pericenter */
            arg_of_pericenter?: number | null;
            /** Mean Anomaly */
            mean_anomaly?: number | null;
            /** Ephemeris Type */
            ephemeris_type?: number | null;
            /** Bstar */
            bstar?: number | null;
            /** Mean Motion Dot */
            mean_motion_dot?: number | null;
            /** Mean Motion Ddot */
            mean_motion_ddot?: number | null;
            /** Semimajor Axis Km */
            semimajor_axis_km?: number | null;
            /** Period Min */
            period_min?: number | null;
            /** Apoapsis Km */
            apoapsis_km?: number | null;
            /** Periapsis Km */
            periapsis_km?: number | null;
            /** Mean Element Theory */
            mean_element_theory?: string | null;
            /** Ref Frame */
            ref_frame?: string | null;
            /** Tle Line0 */
            tle_line0?: string | null;
            /** Tle Line1 */
            tle_line1?: string | null;
            /** Tle Line2 */
            tle_line2?: string | null;
            /** Ingested At */
            ingested_at?: string | null;
        };
        /** Readiness */
        Readiness: {
            status: components["schemas"]["ReadinessStatus"];
            /**
             * Checks
             * @description Per-dependency readiness (e.g. postgres, redis). Empty until wired up.
             */
            checks?: {
                [key: string]: boolean;
            };
        };
        /**
         * ReadinessStatus
         * @enum {string}
         */
        ReadinessStatus: "ready" | "not_ready";
        /** ServiceInfo */
        ServiceInfo: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
        /** StateObject */
        StateObject: {
            /** Object Id */
            object_id?: string | null;
            /** Object Name */
            object_name?: string | null;
            /** Lat Deg */
            lat_deg: number;
            /** Lon Deg */
            lon_deg: number;
            /** Alt Km */
            alt_km: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    service_info__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInfo"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    get_catalog_catalog_get: {
        parameters: {
            query?: {
                /** @description Name / intl-designator / NORAD substring */
                q?: string | null;
                /** @description PAYLOAD / ROCKET BODY / DEBRIS / ... */
                object_type?: string | null;
                country_code?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogObject"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_detail_catalog__object_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_history_catalog__object_id__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_latest_state_catalog__object_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateObject"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_ingest_ingest_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
        };
    };
    get_latest_state_state_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestState"];
                };
            };
        };
    };
    state_stream_state_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    alerts_stream_alerts_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
