/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service information */
        get: operations["service_info__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current catalog */
        get: operations["get_catalog_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Celestrak ingest */
        post: operations["run_ingest_ingest_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest propagated state */
        get: operations["get_latest_state_state_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alert stream (SSE) */
        get: operations["alerts_stream_alerts_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CatalogObject */
        CatalogObject: {
            /** Object Id */
            object_id: string;
            /** Norad Cat Id */
            norad_cat_id?: number | null;
            /** Object Name */
            object_name: string;
            /** Object Type */
            object_type?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Tle Line0 */
            tle_line0?: string | null;
            /** Tle Line1 */
            tle_line1?: string | null;
            /** Tle Line2 */
            tle_line2?: string | null;
        };
        /** IngestResult */
        IngestResult: {
            /** Written */
            written: number;
        };
        /** LatestState */
        LatestState: {
            /** Generated At */
            generated_at?: string | null;
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Objects */
            objects?: components["schemas"]["StateObject"][];
        };
        /** Liveness */
        Liveness: {
            /** @default ok */
            status: components["schemas"]["LivenessStatus"];
        };
        /**
         * LivenessStatus
         * @enum {string}
         */
        LivenessStatus: "ok";
        /** Readiness */
        Readiness: {
            status: components["schemas"]["ReadinessStatus"];
            /**
             * Checks
             * @description Per-dependency readiness (e.g. postgres, redis). Empty until wired up.
             */
            checks?: {
                [key: string]: boolean;
            };
        };
        /**
         * ReadinessStatus
         * @enum {string}
         */
        ReadinessStatus: "ready" | "not_ready";
        /** ServiceInfo */
        ServiceInfo: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
        /** StateObject */
        StateObject: {
            /** Object Id */
            object_id?: string | null;
            /** Object Name */
            object_name?: string | null;
            /** Lat Deg */
            lat_deg: number;
            /** Lon Deg */
            lon_deg: number;
            /** Alt Km */
            alt_km: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    service_info__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInfo"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    get_catalog_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogObject"][];
                };
            };
        };
    };
    run_ingest_ingest_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
        };
    };
    get_latest_state_state_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestState"];
                };
            };
        };
    };
    alerts_stream_alerts_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
